/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SmmPanelRouteImport } from './routes/smm-panel'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PhysicalProductsRouteImport } from './routes/physical-products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GiveawaysRouteImport } from './routes/giveaways'
import { Route as CoursesHubRouteImport } from './routes/courses-hub'
import { Route as AffiliateProgramRouteImport } from './routes/affiliate-program'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CourseSlugRouteImport } from './routes/course.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin.enrollments'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminCoursesIdRouteImport } from './routes/admin.courses.$id'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SmmPanelRoute = SmmPanelRouteImport.update({
  id: '/smm-panel',
  path: '/smm-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicalProductsRoute = PhysicalProductsRouteImport.update({
  id: '/physical-products',
  path: '/physical-products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveawaysRoute = GiveawaysRouteImport.update({
  id: '/giveaways',
  path: '/giveaways',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesHubRoute = CoursesHubRouteImport.update({
  id: '/courses-hub',
  path: '/courses-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateProgramRoute = AffiliateProgramRouteImport.update({
  id: '/affiliate-program',
  path: '/affiliate-program',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CourseSlugRoute = CourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesIdRoute = AdminCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate-program': typeof AffiliateProgramRoute
  '/courses-hub': typeof CoursesHubRoute
  '/giveaways': typeof GiveawaysRoute
  '/login': typeof LoginRoute
  '/physical-products': typeof PhysicalProductsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smm-panel': typeof SmmPanelRoute
  '/tools': typeof ToolsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/course/$slug': typeof CourseSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate-program': typeof AffiliateProgramRoute
  '/courses-hub': typeof CoursesHubRoute
  '/giveaways': typeof GiveawaysRoute
  '/login': typeof LoginRoute
  '/physical-products': typeof PhysicalProductsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smm-panel': typeof SmmPanelRoute
  '/tools': typeof ToolsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/course/$slug': typeof CourseSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate-program': typeof AffiliateProgramRoute
  '/courses-hub': typeof CoursesHubRoute
  '/giveaways': typeof GiveawaysRoute
  '/login': typeof LoginRoute
  '/physical-products': typeof PhysicalProductsRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smm-panel': typeof SmmPanelRoute
  '/tools': typeof ToolsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/course/$slug': typeof CourseSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/affiliate-program'
    | '/courses-hub'
    | '/giveaways'
    | '/login'
    | '/physical-products'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/smm-panel'
    | '/tools'
    | '/admin/courses'
    | '/admin/enrollments'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/course/$slug'
    | '/admin/'
    | '/admin/courses/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliate-program'
    | '/courses-hub'
    | '/giveaways'
    | '/login'
    | '/physical-products'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/smm-panel'
    | '/tools'
    | '/admin/courses'
    | '/admin/enrollments'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/course/$slug'
    | '/admin'
    | '/admin/courses/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/affiliate-program'
    | '/courses-hub'
    | '/giveaways'
    | '/login'
    | '/physical-products'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/smm-panel'
    | '/tools'
    | '/admin/courses'
    | '/admin/enrollments'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/users'
    | '/course/$slug'
    | '/admin/'
    | '/admin/courses/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AffiliateProgramRoute: typeof AffiliateProgramRoute
  CoursesHubRoute: typeof CoursesHubRoute
  GiveawaysRoute: typeof GiveawaysRoute
  LoginRoute: typeof LoginRoute
  PhysicalProductsRoute: typeof PhysicalProductsRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SmmPanelRoute: typeof SmmPanelRoute
  ToolsRoute: typeof ToolsRoute
  CourseSlugRoute: typeof CourseSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smm-panel': {
      id: '/smm-panel'
      path: '/smm-panel'
      fullPath: '/smm-panel'
      preLoaderRoute: typeof SmmPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical-products': {
      id: '/physical-products'
      path: '/physical-products'
      fullPath: '/physical-products'
      preLoaderRoute: typeof PhysicalProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giveaways': {
      id: '/giveaways'
      path: '/giveaways'
      fullPath: '/giveaways'
      preLoaderRoute: typeof GiveawaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses-hub': {
      id: '/courses-hub'
      path: '/courses-hub'
      fullPath: '/courses-hub'
      preLoaderRoute: typeof CoursesHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-program': {
      id: '/affiliate-program'
      path: '/affiliate-program'
      fullPath: '/affiliate-program'
      preLoaderRoute: typeof AffiliateProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/course/$slug': {
      id: '/course/$slug'
      path: '/course/$slug'
      fullPath: '/course/$slug'
      preLoaderRoute: typeof CourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$id': {
      id: '/admin/courses/$id'
      path: '/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AdminCoursesIdRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
  }
}

interface AdminCoursesRouteChildren {
  AdminCoursesIdRoute: typeof AdminCoursesIdRoute
}

const AdminCoursesRouteChildren: AdminCoursesRouteChildren = {
  AdminCoursesIdRoute: AdminCoursesIdRoute,
}

const AdminCoursesRouteWithChildren = AdminCoursesRoute._addFileChildren(
  AdminCoursesRouteChildren,
)

interface AdminRouteChildren {
  AdminCoursesRoute: typeof AdminCoursesRouteWithChildren
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoursesRoute: AdminCoursesRouteWithChildren,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AffiliateProgramRoute: AffiliateProgramRoute,
  CoursesHubRoute: CoursesHubRoute,
  GiveawaysRoute: GiveawaysRoute,
  LoginRoute: LoginRoute,
  PhysicalProductsRoute: PhysicalProductsRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SmmPanelRoute: SmmPanelRoute,
  ToolsRoute: ToolsRoute,
  CourseSlugRoute: CourseSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
